### ISSUE TITLE
Warning on Sticky Nav configuration page

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stickynav#12]
Warning on Sticky Nav configuration page on first visit (when no themes are yet selected): 

> Warning: Invalid argument supplied for foreach() in form_type_checkboxes_value() (line 2443 of /app/core/includes/form.inc).

**Comment by yorkshire-pudding** [comment]
@laryn -  Still getting this. I think the module is overdue for a release.

**Comment by laryn** [comment]
@yorkshire-pudding Whoops! Have you tested the latest dev and is everything looking and working well?

**Comment by yorkshire-pudding** [comment]
Works well on PHP 7.4 but see #15 for issue on PHP 8; I think its related but not sure how.  I had a quick look, but couldn't spot any easy fix.

**Comment by laryn** [comment]
I'll close this one again then and after we get a fix for #15 I'll make a new release.
