### ISSUE TITLE
PHP 8 - Deprecated function: preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in backdrop_match_path()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/stickynav#15]
**Steps to reproduce**

1. PHP 8.1
2. Ensure all errors set to display.
3. Download and enable

**Actual** 
Deprecated function: preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in backdrop_match_path() (line 311 of /app/docroot/core/includes/path.inc).

Once settings enabled for a theme, it goes away.

**Expected**
No errors

This appears to be where it is called from:
https://github.com/backdrop-contrib/stickynav/blob/e0c39dc0f53cc080404003f9c8fd4b5fed6b4f74/stickynav.module#L92-L105

**Comment by yorkshire-pudding** [comment]
@laryn - PR added to fix. Just needed to add a couple of items to the default config.

**Comment by laryn** [comment]
@yorkshire-pudding Thanks for tracking that down!

We have over 100 installations so I'm wondering if it might make sense to also include an update hook to check if there is a value for these settings, and if not to add the defaults. Just in case any existing installations are running into this, or will when they update their PHP.

**Comment by laryn** [comment]
Or is that overkill -- the error goes away as soon as settings are saved, right? Is this a warning or a fatal error?

**Comment by yorkshire-pudding** [comment]
It's just a deprecation notice - might only show up on dev sites with error display switched on. As you say, once the config is saved once it goes away.

**Comment by yorkshire-pudding** [comment]
And how many of those 100 will be unconfigured on PHP 8.1 sites?

**Comment by laryn** [comment]
Okay, I'm convinced.
