### ISSUE TITLE
Make Stickynav work on Basis out of the box

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/stickynav#5]
I've tried Stickynav on three themes (including Basis) and it never seems to work on the .l-header item, which seems to be the mostly logical element for it to work on. This is the one element that spans the entire width of the screen on most sites and can easily be given a background color. 

I've found that it works well on the .l-header-inner element, but this element does not span the width of the page and is not the best element to give a background color. 

It seems to me, that as it comes, Stickynav is almost never useful without some creative theming to go with it. 

It would be great to have a module like this that works on Basis without much tinkering. Am I simply missing the right way to configure it?

**Comment by laryn** [comment]
@stpaultim Yes, agreed, that is how it should work ideally! I have used this on a few sites and didn't notice the issue (likely due to the way I implemented) but I agree that getting this working out of the box on Basis would be important. 

Is this an issue with Basis or with the Layout? e.g. I'm using it [here](https://stuartcenter.org/) in a sub-theme of Basis and on the `.l-header` element with no issues, but I'm also using a custom layout (though built off of Boxton).

**Comment by stpaultim** [comment]
> Is this an issue with Basis or with the Layout?

I am not sure yet. I'll see if I can figure out what the problem is (later). I tried it on different themes, but I don't think I tried different layouts.

**Comment by stpaultim** [comment]
OK, I've tried it on different themes and with different layouts within Basis. Same behavior all the time. I get this warning in the console:

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by laryn** [comment]
@stpaultim Are you able to test with Hero Layouts?
https://backdropcms.org/project/hero

**Comment by laryn** [comment]
(I will try to test further but am largely out of the office for a little while here)

**Comment by stpaultim** [comment]
I did a quick test with hero layout and it did not seem to help. But, I should test when I have more time. I asked a colleague to look at this problem and submit a PR if he has any ideas, since we need this to work on a site we are about to launch. We could do custom solution, but I suggested we try to help fix this module.

**Comment by laryn** [comment]
@stpaultim I had a chance to look at this and it seems basis settings for `.l-header` override the CSS provided by this module. While I'm not a fan of using `!important` in CSS, I can't really think of another way to override this reliably out of the box. Can you verify that changing the `position` line of the [stickynav CSS](https://github.com/backdrop-contrib/stickynav/blob/master/css/stickynav.css#L2) from this:

`position: fixed;`

to this:

`position: fixed !important;`

works for you?

**Comment by stpaultim** [comment]
@laryn  - I understand the reluctance to use !important, but yes that worked for me.

**Comment by laryn** [comment]
@stpaultim Does this work for you as well?
https://github.com/backdrop-contrib/stickynav/commit/e86752fdc002c4176782f401d7083f4f2c515a0a
