### ISSUE TITLE
Explain Jquery format

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/stickynav#6]
The help text for this module says to enter a class using the Jquery format. That confused me, I wasn't exactly sure what you meant. I assumed it was something different from what I am used to as someone that seldom writes custom Jquery. 

The fact that ".l-header" was all I needed was a relief, but not my first try -without the help text it probably would have been my first try. How about adding an example:

> Place your selector for your menu that will be sticky on your theme. Use jquery format (example: .l-header, [another useful example], [maybe one more useful example]).

![Sticky_Nav_Settings___Starter](https://user-images.githubusercontent.com/3144571/65000563-ae80d300-d8b1-11e9-859d-3974b609befc.png)

**Comment by laryn** [comment]
I'm definitely open to this.

**Comment by laryn** [comment]
@stpaultim How does this look to you? Via https://github.com/backdrop-contrib/stickynav/commit/e62f14dfaff787664634eebf077902d6501ae88e

![Screen Shot 2019-09-30 at 4 04 02 PM](https://user-images.githubusercontent.com/871421/65916969-f9afe100-e39b-11e9-9ae5-0c9fa2af7473.jpg)

**Comment by stpaultim** [comment]
That is much better. Thanks.
